### ISSUE TITLE
Hello, when I run testvideo.py, it shows:TypeError: DCNv2Pack() takes no arguments.

### ISSUE THREAD

**Issue by yike5022** [Scatteredrain/SALI#3]
Traceback (most recent call last):
  File "./SALI-main/test_video.py", line 45, in <module>
    model = Network(opt)
  File "./SALI-main/lib/model.py", line 176, in __init__
    self.pcd_align = PCDAlignment(num_feat=32, deformable_groups=8)
  File "./SALI-main/lib/model.py", line 47, in __init__
    self.dcn_pack[level] = DCNv2Pack(
TypeError: DCNv2Pack() takes no arguments
I opened the definition file of the DCNv2Pack class and found that its __init__() constructor does not accept any arguments.

**Comment by Scatteredrain** [comment]
hello, maybe you need to check if there is something wrong with your cuda extensions installation as suggested by Usage-step.1?

**Comment by TJTwonderfulday** [comment]
Hi, I'm having the same problem, have you solved this one yet?
